# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name:                hs-git-clone
version:             0.1.0.0
license:             BSD3

dependencies:
- base >= 4.7 && < 5
# - HUnit
# - async  # may help with concurrency
# - attoparsec
# - bytestring  # useful to send bytes over the network
# - containers  # may help with the database structure and debugging
# - cryptonite
- directory
- filepath
# - http-client
# - http-client-tls
# - http-types
# - megaparsec
# - memory
# - mtl  # may help with structuring
# - parsec
# - parser-combinators
# - text  # use Text rather than String
# - time  # may help with the expiry function
# - word8
# - zlib

executables:
  hs-git-clone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hs-git-clone-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
