name: Post diffs

on:
  pull_request:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  post_diffs:
    uses: codecrafters-io/course-sdk/.github/workflows/post-diffs-in-pr.yml@nikandfor/post_diffs_update
    with:
      sdkRef: nikandfor/post_diffs_update
